apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: backend
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: config
data:
  PORT: "3001"
  NODE_ENV: "production"
  SERVICE_NAME: "auth-service"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
