apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-config
  namespace: backend
  labels:
    app.kubernetes.io/name: email-service
    app.kubernetes.io/component: config
data:
  PORT: "3005"
  NODE_ENV: "production"
  SERVICE_NAME: "email-service"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_FROM: "FanVault Store <jayabaaskar@gmail.com>"
