apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: backend
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/component: config
data:
  PORT: "3004"
  NODE_ENV: "production"
  SERVICE_NAME: "order-service"
  EMAIL_SERVICE_URL: "http://email-service.backend.svc.cluster.local:3005"
