apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: backend
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: config
data:
  PORT: "3003"
  NODE_ENV: "production"
  SERVICE_NAME: "product-service"
