apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: backend
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: config
data:
  PORT: "3002"
  NODE_ENV: "production"
  SERVICE_NAME: "user-service"
