# ──────────────────────────────────────────────────────────────────
# product-service Secret
# ──────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: backend
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://fanvault_admin:FanVault_Secure_2025!@mongodb.db.svc.cluster.local:27017/product-db?authSource=admin&replicaSet=rs0"
  JWT_SECRET: "0b849786adec5efb97547d99e6d76438cf37559eee750d23261abf614456a7dd0d07bb3d59560c20df4ece773a398b13"
