# ──────────────────────────────────────────────────────────────────
# user-service Secret
# ──────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: backend
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:root%40123@mongodb.fanvault-db.svc.cluster.local:27017/user-db?authSource=admin&replicaSet=rs0"
  JWT_SECRET: "0b849786adec5efb97547d99e6d76438cf37559eee750d23261abf614456a7dd0d07bb3d59560c20df4ece773a398b13"
  INTERNAL_SECRET: "d742b8e49bb41080791928716d5b426bf135907ff3a5b7bcf7e89b5012b089d4"
