{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ . }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: {{ $.Values.partOf | default "fanvault" }}
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
{{- end }}
